version: '3'
services:
    elastic:
      #image: elasticsearch:6.4.2
      image: elasticsearch:6.5.4
      hostname: elastic
      restart: always
      volumes:
        - ./elasticsearch/data:/usr/share/elasticsearch/data
      environment:
        discovery.type: single-node

