metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

processors:
- add_cloud_metadata:

output.elasticsearch:
  hosts: ['elastic:9200']
  username: elastic
  password: changeme
setup.kibana:
    host: "http://kibana:5601"
